apiVersion: v1
kind: Service
metadata:
  name: moviesapp-service
spec:
  selector:
    app:  moviesapp
  ports:
    # By default and for convenience, the 'target port' is set to the same value as the 'port' field
    - name: https
      port: 443
      targetPort: 8080
